# Generated by Django 4.2.28 on 2026-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('upload_path', models.CharField(max_length=255)),
                ('result_path', models.CharField(max_length=255)),
                ('vehicle_count', models.IntegerField()),
                ('density_percentage', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('car_count', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=0)),
                ('bus_count', models.IntegerField(default=0)),
                ('motorcycle_count', models.IntegerField(default=0)),
                ('left_lane_count', models.IntegerField(default=0)),
                ('middle_lane_count', models.IntegerField(default=0)),
                ('right_lane_count', models.IntegerField(default=0)),
                ('left_lane_density', models.FloatField(default=0.0)),
                ('middle_lane_density', models.FloatField(default=0.0)),
                ('right_lane_density', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'db_table': 'analysis',
                'ordering': ['-processed_at'],
            },
        ),
    ]
