# Generated by Django 4.2.28 on 2026-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='left_lane_count',
            new_name='east_count',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='left_lane_density',
            new_name='east_density',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='middle_lane_count',
            new_name='north_count',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='middle_lane_density',
            new_name='north_density',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='right_lane_count',
            new_name='south_count',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='right_lane_density',
            new_name='south_density',
        ),
        migrations.AddField(
            model_name='analysis',
            name='west_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='west_density',
            field=models.FloatField(default=0.0),
        ),
    ]
