# Generated by Django 4.2.28 on 2026-02-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_left_lane_count_analysis_east_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='time_series_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
